[project]
name = "rusvox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "datasets==3.6.0",
    "jiwer>=4.0.0",
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
]
